function [edata, practice_data] = bar1_data_finish_practice(edata, practice_data)
% Add all necessary columns, change column format and order

%% columns added by this function       

    % general tracking values
        % subject id
        % trial number
                
    % needed for experiment framework
        % start time (the GetSecs when the trial starts)
        % duration (GetSecs when the trial ends minus start time)
        % complete (true or false)
        
    % bar fill task
        % ssd - stop signal delay (NaN for go trials)
        % left_rt - lift time of left hand
        % right_rt - lift time of right hand
        % outcome - string describing outcome of the trial
        % correct - true/false indicating if trial was performed correctly
            
%% column reordering        
        
    % the column_order cell array determines the order of the columns in trial_data.
    %
    % column order of datasets does not matter to matlab*, this is just for user
    % convenience. [ *NOTE: ...as long as you are using column-name referencing in 
    % your code, like data(:, 'trial_num') as opposed to column-number referencing
    % like data(:, 1) ]
    %
    % column_order is used by code at the end of this function to change the column
    % order. To protect against omissions, an error is thrown if column_order contains
    % a name that is not in the data itself, or the data contains a column that is not
    % listed in column_order.
    
    column_order = { ...
        'subject', ...
        'block', ...
        'trial_num', ...
        'trial_type', ...
        'stop_side', ...
        'bar_stop_time', ...
        'stimulation_time_ts', ...
        'stimulation_time_cs', ...
        'ssd', ...
        'start_time', ...
        'duration', ...
        'complete', ...
        'left_rt', ...
        'right_rt', ...
        'outcome', ...
        'correct' ...
        }; % the line above is the only one that should not have a comma in it

%% fix columns

    % add columns that have the same (initial) value for all rows
    practice_data = dataset_add_columns(practice_data, ...
        'subject', edata.subject_id, ...
        'ssd', NaN, ...
        'start_time', NaN, ...
        'duration', NaN, ...
        'complete', false, ...
        'left_rt', NaN, ...
        'right_rt', NaN, ...
        'outcome', 'incomplete', ...
        'correct', NaN ...
        ); % the last line above should not end with a comma

    % clean up column types
    practice_data = dataset_nominalize_fields(practice_data, ...
        {'stop_side', 'outcome'});
    practice_data = dataset_numericize_fields(practice_data, ...
        {'bar_stop_time', 'ssd', 'stimulation_time_ts', 'stimulation_time_cs'});
    
    % add a trial_num column of consecutive integers
    practice_data.trial_num = transpose(1:size(practice_data,1));
    
    
%% redorder columns

    % this is the code that reorders the columns to match the column_order variable
    % at the beginning of the script. Nothing here needs to be customized.

    missing_fields = setxor(get(practice_data, 'VarNames'), column_order);
    if ~isempty(missing_fields)
        fprintf('Bad fields:\n');
        disp(missing_fields)
        error('The above columns are not handled properly in the column reording process')
    end    
    practice_data = practice_data(:, column_order);
    
% %%  write to csv
%     td2csv(trial_data, edata) %convert trial data to csv format
%     cellwrite(filename, cellarray) % write to the csv file
end
